version: 1
disable_existing_loggers: False

formatters:
  simple:
    format: "[%(asctime)s] [%(levelname)-7s] [%(name)s]: %(message)s"

  vpobj:
    format: "[%(asctime)s] [%(levelname)-7s] [%(obj_path)-65s]: %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout

  vpobj_console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: vpobj
    stream: ext://sys.stdout

loggers:
  vpobj:
    level: DEBUG
    handlers: [vpobj_console]
    propagate: False

root:
  level: INFO
  handlers: [console]
