ASR:
  - id: deepgram
    name: Deepgram ASR
    class: services.services.deepgram_asr_service.DeepGramASRService
    schema: schemas/deepgram_asr.yaml
  - id: whisper
    name: Whisper ASR
    class: services.services.whisper_asr_service.WhisperASRService
    schema: schemas/whisper_asr.yaml

TRA:
  - id: google
    name: Google Translate
    class: services.services.google_translator_service.GoogleTranslatorService
    schema: schemas/google_translate.yaml

TTS:
  - id: google
    name: Google TTS
    class: services.services.google_tts_service.GoogleTTSService
    schema: schemas/google_tts.yaml